name: Deploy Images to GHCR

on:
  push:
    tags:
      - "*.*.*"

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build Inventory Image"
        run: |
          docker build . --tag ghcr.io/theleeeo/gql-test-suite:${{github.ref_name}}
          docker push ghcr.io/theleeeo/gql-test-suite:${{github.ref_name}}
