name: Deploy Images to GHCR

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  push-store-image:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build and publish Image"
        run: |
          TAG=${GITHUB_REF_NAME#v}
          REPO_LOWER=${GITHUB_REPOSITORY,,}

          IMAGE_NAME=ghcr.io/$REPO_LOWER:$TAG
          echo "Image name = ${IMAGE_NAME}"

          docker build . --tag $IMAGE_NAME
          docker push $IMAGE_NAME
